name = "tunemeld-worker"
main = "backend/src/index.ts"
compatibility_date = "2024-07-07"

account_id = "b8a3bf4fc8e54308300b0fa9b11a41a1"
workers_dev = true

node_compat = true

[env.production]
workers_dev = false
route = "api.tunemeld.com/*" 

[[env.production.kv_namespaces]]
binding = "MONGO_URI"
id = "1ca9a570209b4d1eb10e06f49e349b77"

[env.production.vars]
MONGO_DATA_API_KEY = "fpmvWMah9mqSs6eXOeSMtViHFRTZkYiK4zGKnW4CkMlEH0NLPhc26F5mEHI4dx0t"
MONGO_DATA_API_ENDPOINT = "https://us-east-1.aws.data.mongodb-api.com/app/data-vuoqyfy/endpoint/data/v1"

[env.development]
workers_dev = true

[[env.development.kv_namespaces]]
binding = "MONGO_URI"
id = "1ca9a570209b4d1eb10e06f49e349b77"

[env.development.vars]
MONGO_DATA_API_KEY = "fpmvWMah9mqSs6eXOeSMtViHFRTZkYiK4zGKnW4CkMlEH0NLPhc26F5mEHI4dx0t"
MONGO_DATA_API_ENDPOINT = "https://us-east-1.aws.data.mongodb-api.com/app/data-vuoqyfy/endpoint/data/v1"
