name: Deploy to Cloudflare

on:
  push:
    paths:
      - 'kv_worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Publish Worker
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        cd kv_worker
        wrangler publish
