name: Playlists ETL

on:
  schedule:
    - cron: '0 17 * * 6'
  workflow_dispatch:  # This line enables manual trigger


jobs:
  run-tasks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Run extract
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "Sourcing API credentials and running extract command..."
        export X_RapidAPI_Host=${API_HOST}
        make run-extract-actions

    - name: Run transform
      run: |
        echo "Building and running transform command..."
        make run-transform-actions
    
    - name: Debug Print JSON file content
      run: cat ./data/bronze/apple_music_edm_bronze.json
    
    - name: Debug Print JSON file content
      run: cat ./data/bronze/spotify_edm_bronze.json
    
    - name: Debug Print JSON file content
      run: cat ./data/bronze/soundcloud_edm_bronze.json

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}  # Adjust this line to match the name of your secret
      run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
            git add .
            git commit -m "Automated data update" -a || echo "No changes to commit"
            git push
  