[phases.setup]
commands = [
  "python3 -m venv venv",
  ". venv/bin/activate",
  "pip install -r requirements.txt",
  "npm install"
]

[phases.build]
commands = [
  ". venv/bin/activate",
  "make format"
]

[phases.start]
commands = [
  ". venv/bin/activate",
  "make prod"
]